### ISSUE TITLE
many undefined when compiling

### ISSUE THREAD

**Issue by jiebanghan** [csunny/dpos#4]
version is  Linux zqh.02.centos7 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

go build -o build/dpos main/dpos.go
# github.com/libp2p/go-libp2p-loggables
../../libp2p/go-libp2p-loggables/loggables.go:19:26: undefined: log.Loggable
../../libp2p/go-libp2p-loggables/loggables.go:20:9: undefined: log.Metadata
../../libp2p/go-libp2p-loggables/loggables.go:27:21: undefined: log.Loggable
../../libp2p/go-libp2p-loggables/loggables.go:28:9: undefined: log.Metadata
../../libp2p/go-libp2p-loggables/loggables.go:33:23: undefined: log.Metadata
../../libp2p/go-libp2p-loggables/loggables.go:38:9: undefined: log.Metadata
# github.com/libp2p/go-libp2p-transport-upgrader
../../libp2p/go-libp2p-transport-upgrader/listener.go:130:9: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
# github.com/libp2p/go-addr-util
../../libp2p/go-addr-util/addr.go:101:5: log.Event undefined (type *log.ZapEventLogger has no field or method Event)
../../libp2p/go-addr-util/addr.go:101:63: undefined: log.Loggable
../../libp2p/go-addr-util/addr.go:106:10: undefined: log.Metadata
../../libp2p/go-addr-util/addr.go:187:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
# github.com/libp2p/go-mplex
../../libp2p/go-mplex/multiplex.go:202:8: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-mplex/multiplex.go:489:8: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-mplex/multiplex.go:501:8: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-mplex/multiplex.go:539:7: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-mplex/stream.go:206:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
# github.com/libp2p/go-libp2p-nat
../../libp2p/go-libp2p-nat/nat.go:186:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
# github.com/libp2p/go-libp2p-secio
../../libp2p/go-libp2p-secio/protocol.go:117:11: log.EventBegin undefined (type *log.ZapEventLogger has no field or method EventBegin)
# github.com/libp2p/go-libp2p-peerstore/pstoremem
../../libp2p/go-libp2p-peerstore/pstoremem/addr_book.go:154:7: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-libp2p-peerstore/pstoremem/addr_book.go:197:7: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
# github.com/libp2p/go-libp2p/p2p/protocol/identify
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:118:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:125:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:188:6: log.Event undefined (type *log.ZapEventLogger has no field or method Event)
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:197:6: log.Event undefined (type *log.ZapEventLogger has no field or method Event)
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:197:67: undefined: log.Metadata
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:223:6: log.Warning undefined (type *log.ZapEventLogger has no field or method Warning)
../../libp2p/go-libp2p/p2p/protocol/identify/id.go:416:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-libp2p/p2p/protocol/identify/id_delta.go:23:6: log.Warning undefined (type *log.ZapEventLogger has no field or method Warning)
../../libp2p/go-libp2p/p2p/protocol/identify/id_delta.go:38:6: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-libp2p/p2p/protocol/identify/id_delta.go:55:7: log.Warningf undefined (type *log.ZapEventLogger has no field or method Warningf)
../../libp2p/go-libp2p/p2p/protocol/identify/id_delta.go:55:7: too many errors
# github.com/libp2p/go-reuseport-transport
../../libp2p/go-reuseport-transport/multidialer.go:103:8: log.Warning undefined (type *log.ZapEventLogger has no field or method Warning)

**Comment by csunny** [comment]
@jiebanghan  Yes, The [libp2p](https://github.com/libp2p/go-libp2p) project hava changed much, I will fix this recently.

**Comment by csunny** [comment]
@jiebanghan  And you can run with tag v0.1.0

just do
```
git clone https://github.com/csunny/dpos.git
git checkout v0.1.0
``` 
And then you can run with readme commands.   The master branch use go mod, i will fix this later.
